name: Build Thesis

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
  schedule:
    - cron: '0 16 * * 1'  # Build every monday, 16:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Build thesis
      uses: xu-cheng/latex-action@v3
      with:
        root_file: thesis.tex
        latexmk_shell_escape: true
        pre_compile: mkdir -p technical/build/content technical/build/technical
